default:
  test: false
  selection:
    signal:
      recoil: 250    # min
      leadak4:
        pt: 100   # min
        eta: 2.4  # max
        nhf: 0.8  # max
        chf: 0.1  # min
      leadak8:
        pt: 250   # min
        eta: 2.4  # max
        mass:
          min: 65
          max: 105
        tau21: 0.5 # min
      mindphijr : 0.5 # min
      dpfcalo : 0.5 # max
    control:
      doublemu:
        mass:
          min: 60
          max: 120
      doubleel:
        mass:
          min: 60
          max: 120
      singlemu:
        mt : 160
      singleel:
        mt: 160
        met: 50
  tau:
    cuts:
      pt: 18
      eta: 2.3
  photon:
    cuts:
      loose:
        pt: 15
        eta: 2.5
      tight:
        pt: 215
        pttrig: 215
        eta: 1.4442
    branch:
      id: Photon_cutBasedBitmap
  muon:
    cuts:
      tight:
        pt : 20
        eta : 2.4
        iso : 0.15
      loose:
        pt : 10
        eta : 2.4
        iso : 0.25
  electron:
    cuts:
      tight:
        pt : 40
        eta : 2.5
      loose:
        pt : 10
        eta : 2.5
        dxy: # https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2
          barrel: 0.05
          endcap: 0.10
        dz: # https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2
          barrel: 0.10
          endcap: 0.20
    branch:
      id: Electron_cutBased
  btag:
    pt: 20
    eta: 2.4
  overlap:
    electron:
      muon:
        clean: false
        dr: 0.3
    photon:
      muon:
        clean: true
        dr: 0.5
      electron:
        clean: true
        dr: 0.5
    tau:
      muon:
        clean: true
        dr: 0.4
      electron:
        clean: true
        dr: 0.4
    ak4:
      muon:
        clean: true
        dr: 0.4
      electron:
        clean: true
        dr: 0.4
      photon:
        clean: true
        dr: 0.4
    btag:
      muon:
        clean: true
        dr: 0.4
      electron:
        clean: true
        dr: 0.4
      photon:
        clean: true
        dr: 0.4
        
  mitigation:
    hem: True

  sf:
    qcd_ew_nlo_w: # QCD x EW k factor for QCD Z
      histogram: kfactor_monojet_qcd_ewk
      file: data/sf/theory/merged_kfactors_wjets.root
    qcd_ew_nlo_z: # QCD x EW k factor for QCD Z
      histogram: kfactor_monojet_qcd_ewk
      file: data/sf/theory/merged_kfactors_zjets.root
    ewk_nlo_w: # EW k factor for QCD W
      histogram: kfactor_monojet_ewk
      file: data/sf/theory/merged_kfactors_wjets.root
    ewk_nlo_z: # EW k factor for QCD Z
      histogram: kfactor_monojet_ewk
      file: data/sf/theory/merged_kfactors_zjets.root
    ewk_nlo_g: # EW k factor for QCD photon
      histogram: kfactor_monojet_ewk
      file: data/sf/theory/merged_kfactors_gjets.root
    qcd_nlo_w_2017: # QCD k factor for QCD W
      histogram: wjet_dress_monojet
      file: data/sf/theory/2017_gen_v_pt_qcd_sf.root
    qcd_nlo_z_2017: # QCD k factor for QCD Z
      histogram: dy_dress_monojet
      file: data/sf/theory/2017_gen_v_pt_qcd_sf.root

    qcd_nlo_g:
      histogram: kfactor_monojet_qcd
      file: data/sf/theory/merged_kfactors_gjets.root
    qcd_nnlo_g:
      histogram: aj
      file: data/sf/theory/lindert_qcd_nnlo_sf.root
    qcd_nnlo_w:
      histogram: evj
      file: data/sf/theory/lindert_qcd_nnlo_sf.root
    qcd_nnlo_z:
      histogram: eej
      file: data/sf/theory/lindert_qcd_nnlo_sf.root
    pileup:
      mode: nano

  run:
    sync: False
    save:
      passing: False
      tree: False
    kinematics:
      save: False
      events:
        - 36533896
        - 35733274
        - 35719982
        - 30682767
        - 79123963
        - 51393664
    trigger_study: False
    monov: False
    monoj: True
  triggers:
    ht:
      gammaeff:
      - HLT_PFHT1050
      - HLT_PFHT590
      - HLT_PFHT680
      - HLT_PFHT780
      - HLT_PFHT890

env:
  test: false

global:
  test: false


era2016:
  triggers:
    met:
      - HLT_PFMETNoMu90_PFMHTNoMu90_IDTight
      - HLT_PFMETNoMu100_PFMHTNoMu100_IDTight
      - HLT_PFMETNoMu110_PFMHTNoMu110_IDTight
      - HLT_PFMETNoMu120_PFMHTNoMu120_IDTight
    electron:
      single:
        - HLT_Ele27_WPTight_Gsf
        - HLT_Ele105_CaloIdVT_GsfTrkIdT
      single_backup: []
    muon:
      single:
        - HLT_IsoMu27
    photon:
      single:
        - HLT_Photon165_HE10
        - HLT_Photon175
  btag:
    algo: csvv2
    wp: medium
    cuts:
      deepcsv: # https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation2016Legacy
        loose : 0.2217
        medium: 0.6321
        tight: 0.8953
      csvv2:
        loose:  0.5426
        medium: 0.8484
        tight: 0.9535
  wtag: # https://indico.cern.ch/event/840827/contributions/3527925/attachments/1895214/3126510/DeepAK8_Top_W_SFs_2017_JMAR_PK.pdf
      loose: 0.526
      tight: 0.973
      loosemd: 0.184
      tightmd: 0.759
  electron:
    branch:
      id: Electron_cutBased
  photon:
    branch:
      id: Photon_cutBased
  sf:
    qcd_nlo_w_2016: # QCD k factor for QCD W
      histogram: kfactor_monojet_qcd
      file: data/sf/theory/merged_kfactors_wjets.root
    qcd_nlo_z_2016: # QCD k factor for QCD Z
      histogram: kfactor_monojet_qcd
      file: data/sf/theory/merged_kfactors_zjets.root

    ele_reco:
      histogram: EGamma_SF2D
      file: data/sf/egamma/EGM2D_BtoH_GT20GeV_RecoSF_Legacy2016.root
    ele_id_loose:
      histogram: EGamma_SF2D
      file: data/sf/egamma/2016_ElectronWPVeto_Fall17V2.root
    ele_id_tight:
      histogram: EGamma_SF2D
      file: data/sf/egamma/2016LegacyReReco_ElectronTight_Fall17V2.root

    photon_id_tight:
      histogram: EGamma_SF2D
      file: data/sf/egamma/Fall17V2_2016_Medium_photons.root
    photon_csev: # https://twiki.cern.ch/twiki/bin/view/CMS/EgammaIDRecipesRun2#Electron_Veto_CSEV_or_pixel_seed
      histogram: Scaling_Factors_CSEV_R9_Inclusive
      file: data/sf/egamma/ScalingFactors_80X_Summer16_rename.root

    muon_id_loose:
      histogram: NUM_LooseID_DEN_genTracks_pt_abseta
      file: data/sf/muon/2017_RunBCDEF_SF_ID.root
    muon_id_tight:
      histogram: NUM_TightID_DEN_genTracks_pt_abseta
      file: data/sf/muon/2017_RunBCDEF_SF_ID.root
    muon_iso_tight:
      histogram: NUM_TightRelIso_DEN_TightIDandIPCut_pt_abseta
      file: data/sf/muon/2017_RunBCDEF_SF_ISO.root
    muon_iso_loose:
      histogram: NUM_LooseRelIso_DEN_LooseID_pt_abseta
      file: data/sf/muon/2017_RunBCDEF_SF_ISO.root
    pileup:
      histogram: "sf2017_nominal"
      file: "data/sf/pileup/pileup.root"
    pileup_up:
      histogram: "sf2017_up"
      file: "data/sf/pileup/pileup.root"
    pileup_down:
      histogram: "sf2017_down"
      file: "data/sf/pileup/pileup.root"
    trigger_met:
        histogram: 120pfht_hltmu_1m_2017
        file: data/sf/trigger/met_trigger_sf.root
  filters:
    data:
      - Flag_goodVertices
      - Flag_globalSuperTightHalo2016Filter
      - Flag_HBHENoiseFilter
      - Flag_HBHENoiseIsoFilter
      - Flag_EcalDeadCellTriggerPrimitiveFilter
      - Flag_BadPFMuonFilter
      - Flag_eeBadScFilter
    mc:
      - Flag_goodVertices
      - Flag_globalSuperTightHalo2016Filter
      - Flag_HBHENoiseFilter
      - Flag_HBHENoiseIsoFilter
      - Flag_EcalDeadCellTriggerPrimitiveFilter
      - Flag_BadPFMuonFilter

era2017:
  triggers:
    met:
      - HLT_PFMETNoMu120_PFMHTNoMu120_IDTight # 40.658837867 fb-1
      - HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60
    electron:
      single:
        - HLT_Ele35_WPTight_Gsf
        - HLT_Ele115_CaloIdVT_GsfTrkIdT
      single_backup:
        - HLT_Photon200
    muon:
      single:
        - HLT_IsoMu27
    photon:
      single:
        - HLT_Photon200
  filters:
    data:
      - Flag_goodVertices
      - Flag_globalSuperTightHalo2016Filter
      - Flag_HBHENoiseFilter
      - Flag_HBHENoiseIsoFilter
      - Flag_EcalDeadCellTriggerPrimitiveFilter
      - Flag_BadPFMuonFilter
      - Flag_eeBadScFilter
      - Flag_ecalBadCalibFilterV2
    mc:
      - Flag_goodVertices
      - Flag_globalSuperTightHalo2016Filter
      - Flag_HBHENoiseFilter
      - Flag_HBHENoiseIsoFilter
      - Flag_EcalDeadCellTriggerPrimitiveFilter
      - Flag_BadPFMuonFilter
      - Flag_ecalBadCalibFilterV2

  btag:
    algo: deepcsv
    wp: medium
    cuts:
      csvv2: # https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation94X
        loose : 0.5803
        medium : 0.8838
        tight : 0.9693
      deepcsv: # https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation94X
        loose : 0.1522
        medium: 0.4941
        tight: 0.8001
  wtag: # https://indico.cern.ch/event/840827/contributions/3527925/attachments/1895214/3126510/DeepAK8_Top_W_SFs_2017_JMAR_PK.pdf
      loose: 0.779
      tight: 0.991
      loosemd: 0.313
      tightmd: 0.884
  sf:
    ele_reco:
      histogram: EGamma_SF2D
      file: data/sf/egamma/2017_egammaEffi_txt_EGM2D_runBCDEF_passingRECO.root
    ele_id_loose:
      histogram: EGamma_SF2D
      file: data/sf/egamma/2017_ElectronWPVeto_Fall17V2.root
    ele_id_tight:
      histogram: EGamma_SF2D
      file: data/sf/egamma/2017_ElectronTight.root

    photon_id_tight:
      histogram: EGamma_SF2D
      file: data/sf/egamma/2017_PhotonsMedium.root
    photon_csev: # https://twiki.cern.ch/twiki/bin/view/CMS/EgammaIDRecipesRun2#Electron_Veto_CSEV_or_pixel_seed
      histogram: Medium_ID
      file: data/sf/egamma/CSEV_ScaleFactors_2017.root

    muon_id_loose:
      histogram: NUM_LooseID_DEN_genTracks_pt_abseta
      file: data/sf/muon/2017_RunBCDEF_SF_ID.root
    muon_id_tight:
      histogram: NUM_TightID_DEN_genTracks_pt_abseta
      file: data/sf/muon/2017_RunBCDEF_SF_ID.root
    muon_iso_tight:
      histogram: NUM_TightRelIso_DEN_TightIDandIPCut_pt_abseta
      file: data/sf/muon/2017_RunBCDEF_SF_ISO.root
    muon_iso_loose:
      histogram: NUM_LooseRelIso_DEN_LooseID_pt_abseta
      file: data/sf/muon/2017_RunBCDEF_SF_ISO.root

    wtag_loose: # https://indico.cern.ch/event/840827/contributions/3527925/attachments/1895214/3126510/DeepAK8_Top_W_SFs_2017_JMAR_PK.pdf
        histogram: WTag_2017_loose_ak8_pt
        file: data/sf/ak8/wtag_eff_SF.root
    wtag_loosemd: 
        histogram: WTag_2017_loosemd_ak8_pt
        file: data/sf/ak8/wtag_eff_SF.root
    wtag_tight: 
        histogram: WTag_2017_tight_ak8_pt
        file: data/sf/ak8/wtag_eff_SF.root
    wtag_tightmd: 
        histogram: WTag_2017_tightmd_ak8_pt
        file: data/sf/ak8/wtag_eff_SF.root

    wtag_mistag_loose: 
        histogram: Wmistag_2017_loose_ak8_pt
        file: data/sf/ak8/wtag_mistag_SF.root
    wtag_mistag_loosemd: 
        histogram: Wmistag_2017_loosemd_ak8_pt
        file: data/sf/ak8/wtag_mistag_SF.root
    wtag_mistag_tight: 
        histogram: Wmistag_2017_tight_ak8_pt
        file: data/sf/ak8/wtag_mistag_SF.root
    wtag_mistag_tightmd: 
        histogram: Wmistag_2017_tightmd_ak8_pt
        file: data/sf/ak8/wtag_mistag_SF.root

    pileup:
      histogram: "sf2017_nominal"
      file: "data/sf/pileup/pileup.root"
    pileup_up:
      histogram: "sf2017_up"
      file: "data/sf/pileup/pileup.root"
    pileup_down:
      histogram: "sf2017_down"
      file: "data/sf/pileup/pileup.root"

    trigger_met:
      histogram: 120pfht_hltmu_1m_2017
      file: data/sf/trigger/met_trigger_sf.root

era2018:
  triggers:
    met:
      - HLT_PFMETNoMu120_PFMHTNoMu120_IDTight # 59.735969368 fb-1
      - HLT_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60
    electron:
      single:
        - HLT_Ele32_WPTight_Gsf
        - HLT_Ele115_CaloIdVT_GsfTrkIdT
      single_backup:
        - HLT_Photon200
    muon:
      single:
        - HLT_IsoMu24
    photon:
      single:
        - HLT_Photon200
  filters:
    data:
      - Flag_goodVertices
      - Flag_globalSuperTightHalo2016Filter
      - Flag_HBHENoiseFilter
      - Flag_HBHENoiseIsoFilter
      - Flag_EcalDeadCellTriggerPrimitiveFilter
      - Flag_BadPFMuonFilter
      - Flag_eeBadScFilter
      - Flag_ecalBadCalibFilterV2
    mc:
      - Flag_goodVertices
      - Flag_globalSuperTightHalo2016Filter
      - Flag_HBHENoiseFilter
      - Flag_HBHENoiseIsoFilter
      - Flag_EcalDeadCellTriggerPrimitiveFilter
      - Flag_BadPFMuonFilter
      - Flag_ecalBadCalibFilterV2

  btag:
    algo: deepcsv
    wp: medium
    cuts:
      deepcsv: # https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation102X
        loose : 0.1241
        medium: 0.4184
        tight: 0.7527
  wtag: # https://indico.cern.ch/event/840827/contributions/3527925/attachments/1895214/3126510/DeepAK8_Top_W_SFs_2017_JMAR_PK.pdf
      # No study for 2018 yet, using 2017 values
      loose: 0.779
      tight: 0.991
      loosemd: 0.313
      tightmd: 0.884
  sf:
    ele_reco:
      histogram: EGamma_SF2D
      file: data/sf/egamma/2018_egammaEffi_txt_EGM2D_updatedAll.root
    ele_id_loose:
      histogram: EGamma_SF2D
      file: data/sf/egamma/2018_ElectronWPVeto_Fall17V2.root
    ele_id_tight:
      histogram: EGamma_SF2D
      file: data/sf/egamma/2018_ElectronTight.root

    photon_id_tight:
      histogram: EGamma_SF2D
      file: data/sf/egamma/2018_PhotonsMedium.root
    photon_csev: # https://twiki.cern.ch/twiki/bin/view/CMS/EgammaIDRecipesRun2#Electron_Veto_CSEV_or_pixel_seed
      histogram: eleVeto_SF
      file: data/sf/egamma/CSEV_2018.root

    muon_id_loose:
      histogram: NUM_LooseID_DEN_TrackerMuons_pt_abseta
      file: data/sf/muon/2018_RunABCD_SF_ID.root
    muon_id_loose_stat:
      histogram: NUM_LooseID_DEN_TrackerMuons_pt_abseta_stat
      file: data/sf/muon/2018_RunABCD_SF_ID.root
    muon_id_loose_syst:
      histogram: NUM_LooseID_DEN_TrackerMuons_pt_abseta_syst
      file: data/sf/muon/2018_RunABCD_SF_ID.root
    muon_id_tight:
      histogram: NUM_TightID_DEN_TrackerMuons_pt_abseta
      file: data/sf/muon/2018_RunABCD_SF_ID.root
    muon_id_tight_stat:
      histogram: NUM_TightID_DEN_TrackerMuons_pt_abseta_stat
      file: data/sf/muon/2018_RunABCD_SF_ID.root
    muon_id_tight_syst:
      histogram: NUM_TightID_DEN_TrackerMuons_pt_abseta_syst
      file: data/sf/muon/2018_RunABCD_SF_ID.root
    muon_iso_tight:
      histogram: NUM_TightRelIso_DEN_TightIDandIPCut_pt_abseta
      file: data/sf/muon/2018_RunABCD_SF_ISO.root
    muon_iso_tight_stat:
      histogram: NUM_TightRelIso_DEN_TightIDandIPCut_pt_abseta_stat
      file: data/sf/muon/2018_RunABCD_SF_ISO.root
    muon_iso_tight_sys:
      histogram: NUM_TightRelIso_DEN_TightIDandIPCut_pt_abseta_syst
      file: data/sf/muon/2018_RunABCD_SF_ISO.root
    muon_iso_loose:
      histogram: NUM_LooseRelIso_DEN_LooseID_pt_abseta
      file: data/sf/muon/2018_RunABCD_SF_ISO.root
    muon_iso_loose_stat:
      histogram: NUM_LooseRelIso_DEN_LooseID_pt_abseta_stat
      file: data/sf/muon/2018_RunABCD_SF_ISO.root
    muon_iso_loose_sys:
      histogram: NUM_LooseRelIso_DEN_LooseID_pt_abseta_syst
      file: data/sf/muon/2018_RunABCD_SF_ISO.root

    wtag_loose: # https://indico.cern.ch/event/840827/contributions/3527925/attachments/1895214/3126510/DeepAK8_Top_W_SFs_2017_JMAR_PK.pdf
        histogram: WTag_2018_loose_ak8_pt
        file: data/sf/ak8/wtag_eff_SF.root
    wtag_loosemd: 
        histogram: WTag_2018_loosemd_ak8_pt
        file: data/sf/ak8/wtag_eff_SF.root
    wtag_tight: 
        histogram: WTag_2018_tight_ak8_pt
        file: data/sf/ak8/wtag_eff_SF.root
    wtag_tightmd: 
        histogram: WTag_2018_tightmd_ak8_pt
        file: data/sf/ak8/wtag_eff_SF.root

    wtag_mistag_loose: 
        histogram: Wmistag_2018_loose_ak8_pt
        file: data/sf/ak8/wtag_mistag_SF.root
    wtag_mistag_loosemd: 
        histogram: Wmistag_2018_loosemd_ak8_pt
        file: data/sf/ak8/wtag_mistag_SF.root
    wtag_mistag_tight: 
        histogram: Wmistag_2018_tight_ak8_pt
        file: data/sf/ak8/wtag_mistag_SF.root
    wtag_mistag_tightmd: 
        histogram: Wmistag_2018_tightmd_ak8_pt
        file: data/sf/ak8/wtag_mistag_SF.root

    pileup:
      histogram: "sf2018_nominal"
      file: "data/sf/pileup/pileup.root"
    pileup_up:
      histogram: "sf2018_up"
      file: "data/sf/pileup/pileup.root"
    pileup_down:
      histogram: "sf2018_down"
      file: "data/sf/pileup/pileup.root"

    trigger_met:
      histogram: 120pfht_hltmu_1m_2018
      file: data/sf/trigger/met_trigger_sf.root
