default:
  dynaconf_include:
    - common.yaml
  test: false
  selection:
    signal:
      recoil: 250    # min
      leadak4:
        pt: 100   # min
        eta: 2.4  # max
        nhf: 0.8  # max
        chf: 0.1  # min
      leadak8:
        pt: 250   # min
        eta: 2.4  # max
        mass:
          min: 65
          max: 105
        tau21: 0.5 # min
      mindphijr : 0.5 # min
      dpfcalo : 0.5 # max
    control:
      doublemu:
        mass:
          min: 60
          max: 120
      doubleel:
        mass:
          min: 60
          max: 120
      singlemu:
        mt : 160
      singleel:
        mt: 160
        met: 50
  run:
    sync: False
    save:
      passing: False
    kinematics:
      save: False
      events:
        - 36533896
        - 35733274
        - 35719982
        - 30682767
        - 79123963
        - 51393664
    trigger_study: False
    monov: False


