default:
  dynaconf_include:
    - common.yaml
  test: false
  selection:
    signal:
      recoil: 250    # min
      dijet:
        shape_based:
          mass: 200
          dphi: 1.3
          deta: 1
        cut_based:
          mass: 1300
          dphi: 1.5
          deta: 4
      leadak4:
        pt: 80   # min
        eta: 4.7  # max
        nhf: 0.8  # max
        chf: 0.1  # min
      trailak4:
        pt: 40   # min
        eta: 4.7  # max
        nhf: 999  # max
        chf: -999  # min
      mindphijr : 0.5 # min
      dpfcalo : 0.5 # max
    control:
      doublemu:
        mass:
          min: 60
          max: 120
      doubleel:
        mass:
          min: 60
          max: 120
      singlemu:
        mt : 160
      singleel:
        met: 50 # min
        mt: 160
  sf:
    qcd_nlo_w_ewk:
      histogram: TH2F_kFactor
      file: data/sf/theory/kFactor_WToLNu_pT_Mjj.root
    qcd_nlo_z_ewk:
      histogram: TH2F_kFactor
      file: data/sf/theory/kFactor_ZToNuNu_pT_Mjj.root

  run:
    sync: False
    save:
      passing: False
    kinematics:
      save: False
      events:
        - 36533896
        - 35733274
        - 35719982
        - 30682767
        - 79123963
        - 51393664
